[project]
name = 'Decentralized-Theatrical-Costume-Tracking'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.custume-registry]
path = 'contracts/custume-registry.clar'
clarity_version = 2
epoch = 2.5

[contracts.production-history]
path = 'contracts/production-history.clar'
clarity_version = 2
epoch = 2.5

[contracts.rental-management]
path = 'contracts/rental-management.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
